name: docker-publish
on:
  push:
    tags: ['v**']
    branches: [main]

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Image
      uses: docker/build-push-action@v3
      id: build
      with:
        file: utils/Dockerfile
        context: .
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Docker Metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/algst
        tags: |
          type=sha
          type=ref,event=tag
          type=ref,event=branch

    - name: Publish Image
      uses: docker/build-push-action@v3
      with:
        file: utils/Dockerfile
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
